//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGOR.EntityModel.Entities
{
	using System;
	using System.ComponentModel;

	public partial class Cpu : Component
    {
		[DisplayName("Частота (в ГГц)")]
		public float Frequency { get; set; }

		public override Exception Validate()
		{
			if (base.Validate() is Exception ex) {
				return ex;
			} else if (Frequency <= 0) {
				return new Exception($"Частота процессора не может быть меньше или равна 0 ({Frequency}).");
			}

			return null;
		}
	}
}
