//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGOR.EntityModel.Entities
{
	using System;
	using System.ComponentModel;

	public partial class Drive : Component
	{
		[DisplayName("Объем (в Гб)")]
		public float Capacity { get; set; }

		[DisplayName("Тип")]
		public string Type { get; set; }

		public override Exception Validate()
		{
			if (base.Validate() is Exception ex) {
				return ex;
			} else if (Capacity <= 0) {
				return new Exception($"Объем памяьт не может быть отрицательным или равным 0 ({Capacity}).");
			} else if (string.IsNullOrWhiteSpace(Type)) {
				return new Exception($"Не указан тип накопителя ({Type}).");
			}

			return null;
		}
	}
}
