//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGOR.EntityModel.Entities
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class Manufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manufacturer()
        {
            this.Components = new HashSet<Component>();
        }
    
        public int Id { get; set; }

		[DisplayName("Страна")]
		public string Country { get; set; }

		[DisplayName("Производитель")]
		public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Component> Components { get; set; }

		public Exception Validate()
		{
			if (string.IsNullOrWhiteSpace(Country)) {
				return new Exception($"Не указана страна производителя ({Country}).");
			} else if (string.IsNullOrWhiteSpace(Name)) {
				return new Exception($"Не указано наименование производителя ({Name}).");
			}

			return null;
		}
    }
}
