//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGOR.EntityModel.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MemoryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemoryType()
        {
            this.Rams = new HashSet<Ram>();
            this.Motherboards = new HashSet<Motherboard>();
        }
    
        public int Id { get; set; }

		[DisplayName("Наименование")]
		public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ram> Rams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motherboard> Motherboards { get; set; }

		public Exception Validate()
		{
			if (string.IsNullOrWhiteSpace(Name)) {
				return new Exception($"Не указано наименование типа оперативной памяти ({Name}).");
			}

			return null;
		}
    }
}
