//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGOR.EntityModel.Entities
{
	using System;
	using System.ComponentModel;

	public partial class Motherboard : Component
    {
		[DisplayName("Чипсет")]
		public string Chipset { get; set; }

		[DisplayName("Сокет")]
		public string Socket { get; set; }

		[DisplayName("Тип оперативной памяти")]
		public int MemoryTypeId { get; set; }
    
        public virtual MemoryType MemoryType { get; set; }

		public override Exception Validate()
		{
			if (base.Validate() is Exception ex) {
				return ex;
			} else if (string.IsNullOrWhiteSpace(Chipset)) {
				return new Exception($"Не указан чипсет ({Chipset}).");
			} else if (string.IsNullOrWhiteSpace(Socket)) {
				return new Exception($"Не указан сокет ({Socket}).");
			} else if (MemoryTypeId < 1) {
				return new Exception($"Не укзан тип оперативной памяти ({MemoryTypeId}).");
			}

			return null;
		}
	}
}
