//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGOR.EntityModel.Entities
{
    using System;
    using System.ComponentModel;

	public partial class OrderItem
    {
        public int Id { get; set; }

		[DisplayName("Количество")]
		public int Count { get; set; }

		[DisplayName("Компонент")]
		public int ComponentId { get; set; }

		[DisplayName("Заказ")]
		public int OrderId { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Order Order { get; set; }

		public Exception Validate()
		{
			if (Count < 0) {
				return new Exception($"Число элементов не может быть отрицательным ({Count}).");
			} else if (ComponentId < 1) {
				return new Exception($"Не указн компонент ({ComponentId}).");
			} else if (OrderId < 1) {
				return new Exception($"Не указан заказ ({OrderId}).");
			}

			return null;
		}
    }
}
