//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGOR.EntityModel.Entities
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }

		[DisplayName("ФИО покупателя")]
		public string Customer { get; set; }

		[DisplayName("Дата создания заказа")]
		public System.DateTime OrderMoment { get; set; }

		[DisplayName("Состояние")]
		public string State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }

		public Exception Validate()
		{
			if (string.IsNullOrWhiteSpace(Customer)) {
				return new Exception($"не указано ФИО покупателя ({Customer}).");
			} else if (string.IsNullOrWhiteSpace(State)) {
				return new Exception($"Не указано состояние заказа ({State}).");
			}

			return null;
		}
    }
}
