//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGOR.EntityModel.Entities
{
	using System;
	using System.ComponentModel;

	public partial class Ram : Component
    {
		[DisplayName("Объем (в Гб)")]
		public float Capacity { get; set; }

		[DisplayName("Частота (в ГГц)")]
		public float Frequency { get; set; }

		[DisplayName("Тип")]
		public int MemoryTypeId { get; set; }
    
        public virtual MemoryType Type { get; set; }

		public override Exception Validate()
		{
			if (base.Validate() is Exception ex) {
				return ex;
			} else if (Capacity <= 0) {
				return new Exception($"Объем памяти не можеь быть меньше или равен 0 ({Capacity}).");
			} else if (Frequency <= 0) {
				return new Exception($"Частота памти не может быть меньше или равно 0 ({Frequency}).");
			} else if (MemoryTypeId < 1) {
				return new Exception($"Не указан тип оперативной памяти ({MemoryTypeId}).");
			}

			return null;
		}
	}
}
